### ISSUE TITLE
Erro quando a lista de epubs está vazia.

### ISSUE THREAD

**Issue by alextpedro** [alextpedro/ePubIntegrator#1]
Se a lista de epubs estiver vazia a aplicação manda uma nullReferenceException que não é tratada. 
![image](https://cloud.githubusercontent.com/assets/5782944/5637633/95cbbf18-95f5-11e4-9144-c55eaa872ae6.png)

**Comment by ceelix** [comment]
eu sei mas é secundário se não tens items na lista não vais tar a filtrar na parte do utilizador n faz sentido

há coisas mais importantes a tratar, fiz um bcado a pressa e btw o meu não dá erro
